import { Prisma, User } from '@prisma/client'
import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react'
import prisma from '../lib/prisma'
import { fatcher } from '../utils/fatcher'

export async function getServerSideProps() {
  const users: Prisma.UserUncheckedCreateInput[] = await prisma.user.findMany()
  return {
    props: {
      initilaData: users
    }
  }
}
export default function Home({ initilaData }) {


  const [users, setUsers] = useState<Prisma.UserUncheckedCreateInput[]>(initilaData)
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [role, setRole] = useState()

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const body: Prisma.UserCreateInput = {
      name,
      email,
      password,
      role,
    };
    const user = fatcher('/api/create', {user: body});
    setUsers([...users, body])
    setName('')
    setEmail('')
    setPassword('')
    setRole(null)

  }

  const options = [
    { value: 'ADMIN', label: 'Admin' },
    { value: 'USER', label: 'User' },
  ]

  const handleRoleChange = (e, {value}) => setRole(value)
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <form className="w-50 h-screen flex " onSubmit={handleSubmit}>
        <div>
          <label htmlFor="name">Name</label>
          <input type="text" id="name" value={name} onChange={(e) => setName(e.target.value)} />
        </div>
        <div>
          <label htmlFor="email">Email</label>
          <input type="email" id="email" value={email} onChange={(e) => setEmail(e.target.value)} />
        </div>
        <div>
          <label htmlFor="password">Password</label>
          <input type="password" id="password" value={password} onChange={(e) => setPassword(e.target.value)} />
        </div>
        <div>
          <label htmlFor="role">Role</label>
          <select id="role" value={role} onChange={handleRoleChange}>
            {options.map(option => (
              <option key={option.value} value={option.value}>{option.label}</option>
            ))}
          </select>
        </div>
        <button type="submit">Submit</button>
      </form>
      
      </div>
  )
}
